-- A read marker is scoped to either the channel timeline (NULL) or one thread
-- root. Without this dimension, reading a late message in thread A advances the
-- session-wide timestamp and falsely reports older messages in thread B as read.
ALTER TABLE session_read_state
  ADD COLUMN IF NOT EXISTS thread_parent_id uuid REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE session_read_state
  ADD COLUMN IF NOT EXISTS marker_id uuid DEFAULT gen_random_uuid();
ALTER TABLE session_read_state ALTER COLUMN marker_id SET NOT NULL;
ALTER TABLE session_read_state
  ADD COLUMN IF NOT EXISTS event_version bigint GENERATED BY DEFAULT AS IDENTITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'session_read_state_marker_id_key'
  ) THEN
    ALTER TABLE session_read_state
      ADD CONSTRAINT session_read_state_marker_id_key UNIQUE (marker_id);
  END IF;
END $$;
ALTER TABLE session_read_state
  ADD COLUMN IF NOT EXISTS last_seen_message_id uuid REFERENCES messages(id) ON DELETE CASCADE;

-- Legacy timestamp-only rows cannot distinguish messages created in the same
-- transaction. Choose the earliest id at the newest eligible timestamp: that
-- may under-report an old read but can never claim an unseen sibling.
UPDATE session_read_state receipt
   SET last_seen_message_id = (
     SELECT candidate.id
       FROM messages candidate
      WHERE candidate.session_id = receipt.session_id
        AND candidate.created_at <= receipt.read_at
        AND (
          (receipt.thread_parent_id IS NULL
           AND (candidate.thread_parent_id IS NULL OR candidate.broadcast_to_channel IS TRUE))
          OR
          (receipt.thread_parent_id IS NOT NULL
           AND (candidate.id = receipt.thread_parent_id
                OR candidate.thread_parent_id = receipt.thread_parent_id))
        )
      ORDER BY candidate.created_at DESC, candidate.id ASC
      LIMIT 1
   )
 WHERE receipt.last_seen_message_id IS NULL;
DELETE FROM session_read_state WHERE last_seen_message_id IS NULL;
ALTER TABLE session_read_state ALTER COLUMN last_seen_message_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS session_read_state_user_scope_uidx
  ON session_read_state (session_id, user_id, thread_parent_id) NULLS NOT DISTINCT
  WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS session_read_state_agent_scope_uidx
  ON session_read_state (session_id, agent_id, thread_parent_id) NULLS NOT DISTINCT
  WHERE agent_id IS NOT NULL;

DROP INDEX IF EXISTS session_read_state_user_uidx;
DROP INDEX IF EXISTS session_read_state_agent_uidx;

-- Reverse lookups keep account opt-out and agent FK cascade cleanup indexed.
CREATE INDEX IF NOT EXISTS session_read_state_user_lookup_idx
  ON session_read_state (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS session_read_state_agent_lookup_idx
  ON session_read_state (agent_id) WHERE agent_id IS NOT NULL;
